name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/vfrc2/openscad_builder:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
      volumes:
         - ${{ github.workspace }}:/src
    steps:
    - uses: actions/checkout@v4

    - name: Build stl
      run: make
    
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: models
        path: build/