name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: ghcr.io/vfrc2/openscad_builder:latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make
